/**
 * customer-phone-number-api
 * Customer Phone Number API
 *
 * OpenAPI spec version: 1.0
 * Contact: hagar.zakaria.2011@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    status?: any;
}
